# Generated by Django 5.0.14 on 2026-08-18 06:39

import django.core.validators
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_supervisorauthorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='accent_color',
            field=models.CharField(default='#1E5B94', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9A-Fa-f]{6}$', 'Debe ser un color hex de 6 dígitos, ej. #1E5B94.')]),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=tenants.models.company_logo_upload_path),
        ),
    ]
